name: Python package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.11"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pytest matplotlib
          pip install -e .

      - name: Check installation
        run: |
          python -c "import colorengine; print(colorengine.__file__)"

      - name: Check code formatting with Black
        run: |
          black --check --diff colorengine tests

      - name: Test with pytest
        run: |
          pytest tests/ -v

      - name: Set up micromamba (GitHub Actions only)
        if: runner.os != 'Linux' || !env.ACT
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: "1.5.6-0"
          environment-file: environment.yml
          init-shell: >-
            bash
            powershell
          cache-environment: true
          post-cleanup: "all"

      - name: Test with micromamba (GitHub Actions only)
        if: runner.os != 'Linux' || !env.ACT
        shell: micromamba-shell {0}
        run: |
          pip install -e .
          pytest tests/ -v
